config/routes.rb
Rails.application.routes.draw do
  resources :klassen
  resources :schuelers
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/klasse.rb
class Klasse < ApplicationRecord
  has_many :schuelers
end

app/models/schueler.rb
class Schueler < ApplicationRecord
  belongs_to :klasse
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/klassen_controller.rb
class KlassenController < ApplicationController
  def index
    @klassen=Klasse.all.order('klassenname DESC')
    @NumberOfKlassen=Klasse.count
  end

  def show

  end

  def create
      klasse = Klasse.new(klasse_params)
      if klasse.save
      redirect_to action: "index"
    else
      render action: "index"
    end
  end

  def klasse_params
      params.require(:klasse).permit(:klassenname, :code, :des1, :des2, :des3)
  end

  def new

  end

  def destroy
    if Schueler.where(klasse_id: params[:id]).count > 0
      redirect_to action: "index", error: true
    else
     Klasse.find(params[:id]).destroy
     redirect_to action: "index"
    end
  end
end

app/controllers/schuelers_controller.rb
class SchuelersController < ApplicationController
  def index
  @schuelers=Schueler.all.order('name ASC')
  @klasse = Klasse.all
  @NumberOfSchuelers = Schueler.count
  @AverageAge = Schueler.all.average(:age)
  @schuelers=Schueler.all.order('name ASC')
end

def edit
  @schuelers = Schueler.find(params[:id])
  @klassen = Klasse.all
end

def new
  @schuelers=Schueler.all
  @klassen = Klasse.all
end

def create
  schueler= Schueler.new(schueler_params)
  if schueler.save
    redirect_to action: "index"
  else
    render action: "new"
  end
end

def destroy
  Schueler.find(params[:id]).destroy
  redirect_to action: "index"
end

def update
  schueler = Schueler.find(params[:id])
  if schueler.update_attributes(Schueler_params)
    redirect_to action: "index"
  else
    render action: "edit"
  end
end
def schueler_params
  params.require(:schueler).permit(:name, :firstname, :klasse_id, :sex, :age, :email, :des1, :des2, :des3)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/klassen_helper.rb
module KlassenHelper
end

app/helpers/schuelers_helper.rb
module SchuelersHelper
end

app/views/klassen/index.html.erb
<div class="container">
<h3>Klassen</h3>
<table class="table">
  <col class="col-sm-1">
  <tr>
    <%= form_for :klasse, url: {action: "create"}, class: "form-horizontal" do |g| %>
    <tr>
      <td><%=g.label :klassenname, "Klassennamen"%></td>
      <td>
        <%= g.text_field :klassenname, class: "form-control" %>
      </td>
    </tr>
    <tr>
      <td><%=g.label :code, "CODE"%></td>
      <td>
        <%= g.text_field :code, class: "form-control" %>
      </td>
    </tr>
    <tr>
      <td><%=g.label :des1, "Schulhaus"%></td>
      <td>
        <%= g.text_field :des1, class: "form-control" %>
      </td>
    </tr>
    <tr>
      <td><%=g.label :des2, "Schulbeginn"%></td>
      <td>
        <%= g.text_field :des2, class: "form-control" %>
      </td>
    </tr>
    <tr>
      <td><%=g.label :des3, "Schulende"%></td>
      <td>
        <%= g.text_field :des3, class: "form-control" %>
      </td>
    </tr>
    <tr>
      <td><%= g.submit "Save Schueler ", class: "btn btn-success"%>  <% end %></td><td></td>
    </tr>
</table>
<table class="table">
  <col class="col-sm-1">
  <col class="col-sm-1">
  <col class="col-sm-2">
  <col class="col-sm-2">
  <col class="col-sm-2">
  <col class="col-sm-1">

<tr><td><h4>Klasse</h4></td>
  <td><h4>CODE</h4></td>
<td><h4>Schuhaus</h4></td>
<td><h4>Schulbeginn</h4></td>
<td><h4>Schulende</h4></td>

</tr>
<% @klassen.each do |g| %>
    <tr>
      <td><%= g.klassenname %></td>
      <td><%= g.code %></td>
      <td><%= g.des1 %></td>
      <td><%= g.des2 %></td>
      <td><%= g.des3 %></td>
      <td><%= link_to "Delete", klassen_path(g), method: :delete, data: { confirm: "Delete Flight?" } , class: "btn btn-danger"%></td>
    </tr>
  <% end %>
<tr><td>Number of Klassen: <%=@NumberOfKlassen%></td><td></td></tr>
<tr><td><%= link_to "Schüler", schuelers_path, class: "btn btn-success"%></td><td></td></tr>
</table>

app/views/klassen/new.html.erb
<h1>Klassen#new</h1>
<p>Find me in app/views/klassen/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ks</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/schuelers/index.html.erb
<div class="container">
  <h3>Schuelers</h3>
  <table class="table">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <col class="col-sm-1">
    <tr>
      <th>Nr</th>
      <th>FLIGHT</th>
      <th>NAME</th>
      <th>FIRST</th>
      <th>EMAIL</th>
      <th>AGE</th>
      <th>SEX</th>
      <th>PASSPORT</th>
      <th>BIRTH</th>
      <th>RATED</th>
      <th>EDIT</th>
      <th>DESTROY</th>
    </tr>
    <% @schuelers.each do |p| %>
      <tr>
        <td><%= p.id*9776 %></td>
        <td><%=@klasse.find(p.klasse_id).klassenname%></td>
        <td><%= p.name %></td>
        <td><%= p.firstname %></td>
        <td><%= p.email %></td>
        <td><%= p.age %></td>
        <td><%if p.sex %>
            FEMALE
          <%else%>
            MALE
          <%end%></td>
        <td><%= p.des1 %></td>
        <td><%= p.des2 %></td>
        <td>
          <% if p.des3=="WANTED"%>
            <font color="red"><strong><%= p.des3 %><br /> Police is coming!</strong></font>
          <%else%>
          <%= p.des3 %>
        <%end%></td>
        <td><%= link_to "Edit", edit_schueler_path(p) , class: "btn btn-success"%></td>
        <td><%= link_to "Löschen", schueler_path(p), method: :delete, data: { confirm: "DESTROY PERSON?" } , class: "btn btn-danger"%></td>
      </tr>
    <% end %>
    <tr><td colspan="2">NUMBER OF schuelers: </td><td colspan="10"><%= @NumberOfSchuelers %></td></tr>
    <tr><td colspan="2">AVERAGE AGE: </td><td colspan="10"><%= @AverageAge %></td></tr>
    <tr><td colspan="2">FLIGHT: </td><td colspan="8">
      <%@klasse.all.each do |g|%>

          <%i=0%>
        <%@schuelers.all.each do |pp|%>
            <%if pp.klasse_id==g.id%>
                <%i=i+1%>
            <%end%>
          <%end%>
           <%=i%> PASSENGERS ON <%=g.klassenname%><br>
      <%end%>


     </td></tr>
  </table>
  <h4>
    <%= link_to "ADD Schüler", new_schueler_path, class: "btn btn-success"%>
    <%= link_to "Klassen ", klassen_index_path , class: "btn btn-success"%>
  </h4>
</div>

app/views/schuelers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-6">
      <h3>Schueler#new</h3>
    </div>
  </div>
  <%= form_for :schueler, url: {action: "create"}, class: "form-horizontal" do |p| %>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :name, "NAME:" %></div>
    <div class="col-md-7"><%= p.text_field :name, class: "form-control" %><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :firstname, "FIRST:" %></div>
    <div class="col-md-7"><%= p.text_field :firstname, class: "form-control" %><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :klasse_id, "FLIGHT:" %></div>
    <div class="col-md-7"><%= p.collection_select :klasse_id, @klassen, :id, :klassenname, class: "form-control" %><br /><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :email, "EMAIL:" %></div>
    <div class="col-md-7"><%= p.text_field :email, class: "form-control" %><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :age, "AGE:" %></div>
    <div class="col-md-7"><%= p.text_field :age, class: "form-control" %><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1">SEX:</div>
    <div class="col-md-2"><%= p.radio_button :sex, 0, :checked => true %> MALE<br />
      <%= p.radio_button :sex, 1%> FEMALE<br /><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :des1, "PASSPORT:" %></div>
    <div class="col-md-7"><%= p.text_field :des1, class: "form-control" %><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :des2, "BIRTH:" %></div>
    <div class="col-md-7"><%= p.text_field :des2, class: "form-control" %><br /></div>
  </div>
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-1"><%= p.label :des3, "RATED:" %></div>
    <div class="col-md-7"><%= p.text_field :des3, class: "form-control" %><br /></div>
  </div>
  <br />
  <br />
  <div class="row">
    <div class="col-md-2"> </div>
    <div class="col-md-10">
      <%= p.submit "SAVE PASSENGER", class: "btn btn-success"%>
      <%= link_to "CANCEL", schuelers_path, class: "btn btn-danger" %>
    </div>
  </div>
  <% end %>
</div>